CANVAS_URL = "YOUR INSTITUTION'S CANVAS URL GOES HERE" # e.g. https://xcourses.xuniversity.edu/
ACCESS_TOKEN = "YOUR CANVAS ACCESS TOKEN GOES HERE" # See README for how to obtain this

# 1072~3nOf9JP8dkLXiSDyRSsAHAtFYSjFbOkyXOTli4YxQTVUY9OSoPMjBDZ6se47Kjd1